export interface User {
  id: number;
  username: string;
  balance: number;
  firstName: string;
  lastName: string;
  isAdmin: boolean;
}
export const mockedUsers = [
  {
    id: 1,
    username: 'kglenister0',
    firstName: 'Katerina',
    lastName: 'Glenister',
    isAdmin: false,
    balance: 0,
  },
  {
    id: 2,
    username: 'mowens1',
    firstName: 'Mervin',
    lastName: 'Owens',
    isAdmin: false,
    balance: 370,
  },
  {
    id: 3,
    username: 'rmcaneny2',
    firstName: 'Ricard',
    lastName: 'McAneny',
    isAdmin: false,
    balance: 230,
  },
  {
    id: 4,
    username: 'mgillitt3',
    firstName: 'Mirna',
    lastName: 'Gillitt',
    isAdmin: false,
    balance: -20,
  },
  {
    id: 5,
    username: 'sbolland4',
    firstName: 'Sarine',
    lastName: 'Bolland',
    isAdmin: false,
    balance: 570,
  },
  {
    id: 6,
    username: 'varmfield5',
    firstName: 'Virgilio',
    lastName: 'Armfield',
    isAdmin: false,
    balance: 100,
  },
  {
    id: 7,
    username: 'bramme6',
    firstName: 'Beltran',
    lastName: 'Ramme',
    isAdmin: false,
    balance: 180,
  },
  {
    id: 8,
    username: 'gpennyman7',
    firstName: 'Guillermo',
    lastName: 'Pennyman',
    isAdmin: false,
    balance: 510,
  },
  {
    id: 9,
    username: 'gitshak8',
    firstName: 'Gabi',
    lastName: 'Itshak',
    isAdmin: false,
    balance: 300,
  },
  {
    id: 10,
    username: 'kaddams9',
    firstName: 'Keven',
    lastName: 'Addams',
    isAdmin: false,
    balance: -20,
  },
  {
    id: 11,
    username: 'astouthera',
    firstName: 'Agneta',
    lastName: 'Stouther',
    isAdmin: false,
    balance: 330,
  },
  {
    id: 12,
    username: 'sgladdorb',
    firstName: 'Stephi',
    lastName: 'Gladdor',
    isAdmin: false,
    balance: 230,
  },
  {
    id: 13,
    username: 'mruddockc',
    firstName: 'Marysa',
    lastName: 'Ruddock',
    isAdmin: false,
    balance: 190,
  },
  {
    id: 14,
    username: 'dedelerd',
    firstName: 'Donnell',
    lastName: 'Edeler',
    isAdmin: false,
    balance: 530,
  },
  {
    id: 15,
    username: 'ywallbridgee',
    firstName: 'Yorke',
    lastName: 'Wallbridge',
    isAdmin: false,
    balance: -30,
  },
  {
    id: 16,
    username: 'mwillcotf',
    firstName: 'Maegan',
    lastName: 'Willcot',
    isAdmin: false,
    balance: 550,
  },
  {
    id: 17,
    username: 'nboschmanng',
    firstName: 'Napoleon',
    lastName: 'Boschmann',
    isAdmin: false,
    balance: 370,
  },
  {
    id: 18,
    username: 'vskipworthh',
    firstName: 'Vivien',
    lastName: 'Skipworth',
    isAdmin: false,
    balance: -30,
  },
  {
    id: 19,
    username: 'cbusseli',
    firstName: 'Chrisy',
    lastName: 'Bussel',
    isAdmin: false,
    balance: 290,
  },
  {
    id: 20,
    username: 'lcraigsj',
    firstName: 'Lincoln',
    lastName: 'Craigs',
    isAdmin: false,
    balance: 150,
  },
  {
    id: 21,
    username: 'lbedinhamk',
    firstName: 'Lucky',
    lastName: 'Bedinham',
    isAdmin: false,
    balance: 350,
  },
  {
    id: 22,
    username: 'aboltwoodl',
    firstName: 'Atalanta',
    lastName: 'Boltwood',
    isAdmin: false,
    balance: -30,
  },
  {
    id: 23,
    username: 'cbelchemm',
    firstName: 'Carter',
    lastName: 'Belchem',
    isAdmin: false,
    balance: 470,
  },
  {
    id: 24,
    username: 'cgatchelln',
    firstName: 'Chiquia',
    lastName: 'Gatchell',
    isAdmin: false,
    balance: 250,
  },
  {
    id: 25,
    username: 'hlindeo',
    firstName: 'Heddi',
    lastName: 'Linde',
    isAdmin: false,
    balance: -30,
  },
  {
    id: 26,
    username: 'ddifrancescop',
    firstName: 'Danila',
    lastName: 'Di Francesco',
    isAdmin: false,
    balance: 200,
  },
  {
    id: 27,
    username: 'ecraykeq',
    firstName: 'Eric',
    lastName: 'Crayke',
    isAdmin: false,
    balance: 60,
  },
  {
    id: 28,
    username: 'amccormickr',
    firstName: 'Ambrosio',
    lastName: 'McCormick',
    isAdmin: false,
    balance: 210,
  },
  {
    id: 29,
    username: 'mhablots',
    firstName: 'Merrel',
    lastName: 'Hablot',
    isAdmin: false,
    balance: 130,
  },
  {
    id: 30,
    username: 'wguiott',
    firstName: 'Winn',
    lastName: 'Guiot',
    isAdmin: false,
    balance: 130,
  },
] as User[];
